### ISSUE TITLE
TODO/ Wishlist Summary

### ISSUE THREAD

**Issue by rBatt** [rBatt/parking#1]
Top-level summary of potential fixes or enhancements. Items might reference other issues or milestones if sizable enough to merit.

# App
 - [x] Fix empty color polygon
 - [x] Improve color scaling in polygon
 - [x] Add number of tickets
 - [ ] Historical tab
 - [ ] Splash/ images
- [x] Slider appears to be 4 hours behind graph x-axis
- [ ] Select precinct by entering street address
- [ ] Request location to automatically select precinct

# Data
 - [ ] Signage from https://github.com/rBatt/analyze-nyc-parking-signs
 - [ ] Signage shapefile
 - [ ] FY 2018-2019 data

# Analysis
 - [ ] Compare to baseline
 - [ ] VARMAX (running)
 - [ ] Uncertainty
